### ISSUE TITLE
Enough large territory has opened at the first click.

### ISSUE THREAD

**Issue by lomeat** [kana-sama/minecljs#1]
https://user-images.githubusercontent.com/33469504/172060539-b64fb4af-db9a-4bef-a0ca-4c525b35e19c.mp4

https://user-images.githubusercontent.com/33469504/172060580-e120c860-0877-4d6a-b38a-803ce9150f64.mp4

Yet at the latest once noticed that enough large territory has opened with the first click. Example: how it works in original game. Sometimes openes just one cell.

**Comment by kana-sama** [comment]
Это баг оригинальной версии, который сохраняли дальше, и в этой версии я написал дополнительный код, чтобы всегда открывалось больше одной клетки.

```clojure
(defn random-mines [game [start-x start-y]]
  (let [available-cells (-> (all-cells game)
                            (disj [start-x start-y])
                            (difference (cells-around game [start-x start-y])))]
    (random-subset available-cells (:mines-amount game))))
 ```
 
За это отвечает строчка `(difference (cells-around game [start-x start-y])))]`, которая не позволяет ставить бомбы рядом с начальной клеткой, окружение начальной клетки из пула кандидатов для бомб.
